version: '3.7'

services:
  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GRPC_TRACE=http,call_error,connectivity_state
      - GRPC_VERBOSITY=debug
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=otel-collector:4317
    networks:
      - distributed-trace
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
    networks:
      - distributed-trace
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16685:16685"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "9411:9411"
      - "4317"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - distributed-trace

networks:
  distributed-trace:
