version: '3.7'

services:
  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - GRPC_TRACE=http,call_error,connectivity_state
      - GRPC_VERBOSITY=debug
      - OTEL_EXPORTER_OTLP_TRACES_ENDPOINT=otel-collector:4317
    networks:
      - distributed-trace
    depends_on:
      - otel-collector

  otel-collector:
    image: otel/opentelemetry-collector
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317" # OTLP gRPC receiver
    networks:
      - distributed-trace
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16685"
      - "16686:16686"  # Jaeger UI
      - "14250"  # Used by Agent to send spans in model.proto format.
      - "5778"  # Used by Agent component to serve configs
      - "4317"  # Used by Collector component to accept gRPC traces
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - distributed-trace

networks:
  distributed-trace:
