version: '3.7'

services:
  server:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    environment:
      - OTEL_EXPORTER_JAEGER_ENDPOINT=http://jaeger:14268/api/traces
    networks:
      - jaeger-example
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268:14268"
    environment:
      - COLLECTOR_OTLP_ENABLED=true
      - LOG_LEVEL=debug
    networks:
      - jaeger-example

networks:
  jaeger-example:
